logging.file.path=/root/prism/logs
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/sKh8ZLCEc2ea2zNK?useUnicode=true&characterEncoding=UTF-8&useSSL=false
spring.datasource.username=xiFZQAYRL1SyGIPd
spring.datasource.password=NXx4p2VIEILNLONk
jwt.secret=NcSRkrapTUnhda2y
server.port=50000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
